name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          curl -fsSL get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Restore exemplar cache
        uses: actions/cache@v2
        with:
          path: ~/data
          key: ${{ runner.os }}-mcmicro-exemplars
      - name: Download exemplar-001
        run: |
          if [ -d ~/data/exemplar-001 ]; then
            echo "Using cached exemplar-001 download";
          else
            nextflow exemplar.nf --name exemplar-001 --path ~/data;
          fi
      # - name: Download exemplar-002
      #   run: nextflow exemplar.nf --name exemplar-002 --path ~/data
      - name: Store Nextflow executable
        uses: actions/upload-artifact@v2
        with:
          name: nfexe
          path: /usr/local/bin/nextflow
  test-ex001:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Nextflow executable
        uses: actions/download-artifact@v2
        with:
          name: nfexe
      # - name: Test exemplar-001
      #   run: |
      #     cp -r ~/data/downloads/exemplar-001 ~/data/
      #     nextflow main.nf --in ~/data/exemplar-001 --probability-maps all --s3seg-opts '--probMapChan 0'
      #     ls ~/data/exemplar-001/*
